version: 1

filters:
  info_file:
    (): src.insfra.logger.default_logger.InfoFilter
  error_file:
    (): src.insfra.logger.default_logger.ErrorFilter

formatters:
  standard:
    format: '[%(asctime)s]  [%(levelname)6s]  %(message)s'
  error:
    format: "[%(asctime)s]  [%(levelname)6s]  %(message)s"


handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: standard
    stream: ext://sys.stdout

  info_file_handler:
    class: logging.handlers.RotatingFileHandler
    formatter: standard
    level: INFO
    filename: logs/info.log
    encoding: utf8
    mode: "w"
    maxBytes: 10485760 # 10MB
    backupCount: 1
    "filters": ["info_file"]

  error_file_handler:
    class: logging.handlers.RotatingFileHandler
    formatter: error
    level: ERROR
    filename: logs/error.log
    encoding: utf8
    mode: "w"
    maxBytes: 10485760 # 10MB
    backupCount: 1
    "filters": ["error_file"]

loggers:
  dev:
    handlers: [ console ]
    propagate: false
  prod:
    handlers: [ console, info_file_handler, error_file_handler ]
    propagate: false

#root:
#  handlers: [ console, info_file_handler,error_file_handler ]
#  propagate: false